name: Deploy to S3

on:
  push:
    branches:
      - master

  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
    name: Upload to S3
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install
      - run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - if: github.ref == 'refs/heads/master'
        name: Copy files to the root of the bucket
        run: |
          aws s3 sync ./dist s3://research-ops-static-sites --acl public-read
          aws s3 sync ./dist s3://research-ops-static-sites/helpcentre --acl public-read

      - if: github.event_name == 'pull_request'
        name: Copy files of pull request to branch
        run: |
          aws s3 sync ./dist s3://research-ops-static-sites/${{ github.head_ref}}/${{ github.event.pull_request.number }} \
          --acl public-read \

      # - if: success() && github.event_name == 'pull_request'
      #   name: Comment on PR
      #   uses: unsplash/comment-on-pr@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     msg: "Your pull request has been deployed to S3. You can [view it here](https://svy.enginetransformation.com/${{ github.head_ref }}/${{ github.event.pull_request.number }}/index.html) :tada:"
      #     check_for_duplicate_msg: true
